application:
  max: 50
micronaut:
  application:
    name: filmer-srv
  server:
    port: 8086
    cors:
      enabled: true
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            okta:
              url: https://dev-467598.okta.com/oauth2/default/v1/keys
omdb:
  apiKey: dff9dc43
  urlString: "http://www.omdbapi.com"
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jpa:
  default:
    packages-to-scan:
      - 'uk.me.staines.filmer'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true